import { isMac } from "../utils/os";

export const keyMappings: { [key: string]: string } = {
  control: isMac() ? "⌃" : "CTRL",
  alt: isMac() ? "⌥" : "ALT",
  command: isMac() ? "⌘" : "CMD",
  shift: "SHIFT",
  tab: "TAB",
  enter: "ENT",
  escape: "ESC",
  capslock: "CAPS",
  space: "SPC",
  backspace: "BKSP",
  delete: "DEL",
  home: "HM",
  end: "END",
  pageup: "PGUP",
  pagedown: "PGDN",
  insert: "INS",
  fn: "FN",
  meta: isMac() ? "⌘" : "WIN",
  return: "RET",
  printscreen: "PRTSCR",
  numlock: "NUMLK",
  scrolllock: "SCRLK",
  arrowup: "UP",
  arrowdown: "DOWN",
  arrowleft: "LEFT",
  arrowright: "RIGHT",
};
